### ISSUE TITLE
Uploading Files

### ISSUE THREAD

**Issue by charlescrain** [algspd/OctoScript#2]
Files do not get uploaded when upload <filename> command is run. Files can be removed and and connected to the printer but not uploaded.

**Comment by algspd** [comment]
It is working ok for me. Steps to reproduce the error?

**Comment by charlescrain** [comment]
Hmm it is not exactly an error. What happens is that the file specified just does not get uploaded. I thought that perhaps the login info was wrong but since I am able to remove files this does not seem the case. I think it is an http error rather than error with the script. If you don't have any ideas I would love to hear them, if not we should close this issue.

**Comment by algspd** [comment]
Hum... try to run the command standalone on the shell (get it from octoscript, it is just a curl call with some args) and see if it returns any error, or just remove the ">& /dev/null" part, to make it dump its output to the console and copy it here.

**Comment by charlescrain** [comment]
Okay it says "Invalid target: upload"

**Comment by algspd** [comment]
And the command is? :p

**Comment by charlescrain** [comment]
haha my bad here you go:

curl -b cookies.txt "http://$arg_host:$arg_port/ajax/gcodefiles/upload" \
  -F gcode_file=@"$arg_file" #>& /dev/null

I called it with:

./octoscript localhost 5000 upload test1.gcode

**Comment by algspd** [comment]
Ok, confirmed with the last version of OctoPrint.

**Comment by algspd** [comment]
https://github.com/algspd/OctoScript/commit/1885c4eeefad192c1943eb49a61eb2972345438e
